# Generated by Django 5.2.16 on 2026-07-30 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmlCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("threshold", "threshold"),
                            ("velocity", "velocity"),
                            ("structuring", "structuring"),
                            ("manual", "manual"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("investigating", "investigating"),
                            ("filed", "filed"),
                            ("dismissed", "dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("narrative", models.TextField(blank=True, default="")),
                (
                    "nfiu_reference",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("detected", models.DateTimeField(default=django.utils.timezone.now)),
                ("due", models.DateTimeField()),
                ("closed", models.DateTimeField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aml_closures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aml_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due", "-detected"],
                "indexes": [
                    models.Index(fields=["status", "due"], name="aml_status_due_idx"),
                    models.Index(fields=["user", "-detected"], name="aml_user_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("dedupe_key",),
                        name="uniq_aml_dedupe_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("export", "export"), ("erase", "erase")], max_length=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("completed", "completed"),
                            ("refused", "refused"),
                        ],
                        default="received",
                        max_length=10,
                    ),
                ),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("received", models.DateTimeField(default=django.utils.timezone.now)),
                ("due", models.DateTimeField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_requests_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received"],
                "indexes": [
                    models.Index(fields=["status", "due"], name="dsr_status_due_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=64)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_received", "not_received"),
                            ("wrong_amount", "wrong_amount"),
                            ("unauthorised", "unauthorised"),
                            ("duplicate", "duplicate"),
                            ("other", "other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("investigating", "investigating"),
                            ("upheld", "upheld"),
                            ("declined", "declined"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("due", models.DateTimeField()),
                ("resolved", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["status", "due"], name="dispute_status_due_idx"
                    ),
                    models.Index(fields=["reference"], name="dispute_reference_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["open", "investigating"])),
                        fields=("user", "reference"),
                        name="uniq_open_dispute_per_reference",
                    )
                ],
            },
        ),
    ]
