# Generated by Django 5.2.14 on 2026-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bvn_user_bvn_verified_user_face_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
