# Generated by Django 5.2.15 on 2026-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otp_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
