# Generated by Django 5.2.15 on 2026-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_pin_failed_attempts_user_pin_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[("signup", "signup"), ("reset", "reset")],
                default="signup",
                max_length=10,
            ),
        ),
    ]
