# Generated by Django 5.2.15 on 2026-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_otp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
