# Generated by Django 5.2.15 on 2026-06-30 11:36

from django.db import migrations, models


def recompute_tiers(apps, schema_editor):
    """Re-derive every user's tier under the new requirements (Tier 1 = BVN+NIN;
    Tier 2 = +face+address; Tier 3 = +ID document). The new address/ID fields
    default false, so a previously high-tier user holds the tier their existing
    verifications support and regains higher tiers by completing the new steps."""
    User = apps.get_model("accounts", "User")
    for u in User.objects.all().only(
        "id", "tier", "bvn_verified", "nin_verified", "face_verified",
        "address_verified", "id_document_verified",
    ).iterator():
        if (u.bvn_verified and u.nin_verified and u.face_verified
                and u.address_verified and u.id_document_verified):
            t = 3
        elif (u.bvn_verified and u.nin_verified and u.face_verified
                and u.address_verified):
            t = 2
        elif u.bvn_verified and u.nin_verified:
            t = 1
        else:
            t = 0
        if u.tier != t:
            User.objects.filter(pk=u.pk).update(tier=t)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_hash_bvn_nin_at_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="address_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="tier",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(recompute_tiers, migrations.RunPython.noop),
    ]
