# Generated by Django 5.2.15 on 2026-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_address_user_address_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="scope",
            field=models.CharField(
                choices=[("app", "app"), ("admin", "admin")],
                db_index=True,
                default="app",
                max_length=8,
            ),
        ),
    ]
