# Generated by Django 5.2.16 on 2026-07-30 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_hash_otp_codes_at_rest"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("os", models.CharField(blank=True, default="", max_length=16)),
                ("model", models.CharField(blank=True, default="", max_length=48)),
                ("brand", models.CharField(blank=True, default="", max_length=32)),
                ("last_ip", models.CharField(blank=True, default="", max_length=64)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-last_seen"], name="device_user_seen_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_id"), name="uniq_user_device"
                    )
                ],
            },
        ),
    ]
