# Generated by Django 5.2.16 on 2026-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_unique_identity_hashes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarded_via_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[("signup", "signup"), ("reset", "reset"), ("email", "email")],
                default="signup",
                max_length=10,
            ),
        ),
    ]
