# Generated by Django 5.2.16 on 2026-08-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_user_phone_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_reset_required",
            field=models.BooleanField(default=False),
        ),
    ]
