# Generated by Django 5.2.17 on 2026-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="self_txn_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
