# Generated by Django 5.2.17 on 2026-08-17 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_user_self_txn_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("family", models.CharField(db_index=True, max_length=32)),
                ("device_id", models.CharField(blank=True, default="", max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "family_started",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "family"], name="accounts_re_user_id_7842af_idx"
                    )
                ],
            },
        ),
    ]
