# Generated by Django 5.2.17 on 2026-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_identityproof_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_consent_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
