# Generated by Django 5.2.17 on 2026-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_backfill_spend_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityproof',
            name='verified_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
