# Generated by Django 5.2.15 on 2026-06-05 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_fundingintent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="txn_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="wallet_balance_non_negative",
            ),
        ),
    ]
