# Generated by Django 5.2.14 on 2026-06-09 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_transaction_idempotency_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="NGN", max_length=3),
        ),
        migrations.CreateModel(
            name="FxQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_ref",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                ("sell_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "receive_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "currency"), name="uniq_user_currency_wallet"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="currency_wallet_balance_non_negative",
                    ),
                ],
            },
        ),
    ]
