# Generated by Django 5.2.14 on 2026-06-09 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_transaction_currency_fxquote_currencywallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-created"], name="txn_user_created_idx"
            ),
        ),
    ]
