# Generated by Django 5.2.15 on 2026-06-18 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_wallet_reserved_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_number", ""), _negated=True),
                fields=("account_number",),
                name="uniq_wallet_account_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_reference", ""), _negated=True),
                fields=("account_reference",),
                name="uniq_wallet_account_reference",
            ),
        ),
    ]
