# Generated by Django 5.2.15 on 2026-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_wallet_uniq_wallet_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingintent",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
