# Generated by Django 5.2.17 on 2026-08-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0015_wemaprovisioningattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WemaFaceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=64, unique=True)),
                (
                    "identity_type",
                    models.CharField(
                        choices=[("bvn", "BVN"), ("nin", "NIN")], max_length=3
                    ),
                ),
                ("identity_hash", models.CharField(max_length=64)),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("verified", "verified"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wema_face_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "expires_at"],
                        name="wema_face_lookup_idx",
                    )
                ],
            },
        ),
    ]
