# Generated by Django 5.2.17 on 2026-10-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_wemaprovisioningattempt_otp_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('whatsapp', 'whatsapp'), ('push', 'push')], max_length=12)),
                ('state', models.CharField(choices=[('ready', 'ready'), ('preparing', 'preparing'), ('dispatching', 'dispatching'), ('accepted', 'accepted'), ('retry', 'retry'), ('review', 'review'), ('exhausted', 'exhausted'), ('skipped', 'skipped')], default='ready', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_deliveries', to='wallet.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='txn_alert_ready_idx')],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'reversal', 'channel'), name='uniq_txn_alert_channel')],
            },
        ),
    ]
