# Generated by Django 5.2.17 on 2026-10-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_bankhistorycheckpoint'),
        ('wema_vas', '0003_durable_bank_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFundingBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(max_length=10)),
                ('approval_reference', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill_funding', to='wallet.transaction')),
                ('vas_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_fundings', to='wema_vas.virtualaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillFundingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='wallet.billfundingbinding')),
            ],
        ),
        migrations.AddConstraint(
            model_name='billfundingbinding',
            constraint=models.CheckConstraint(condition=models.Q(('source_account__regex', '^[0-9]{10}$')), name='bill_funding_source_account_valid'),
        ),
    ]
