# Generated by Django 5.1.15 on 2026-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BettingPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
                ("service_id", models.CharField(blank=True, default="", max_length=40)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
