# Generated by Django 5.2.14 on 2026-06-09 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msisdn", models.CharField(db_index=True, max_length=20)),
                ("action_type", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_pending_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msisdn", models.CharField(db_index=True, max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")], max_length=3
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("intent_json", models.JSONField(blank=True, default=dict)),
                ("flagged", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("wa_message_id", ""), _negated=True),
                        fields=("wa_message_id",),
                        name="uniq_wa_message_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_msisdn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("active", "active")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "link_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("ai_enabled", models.BooleanField(default=True)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "active"),
                            models.Q(("wa_msisdn", ""), _negated=True),
                        ),
                        fields=("wa_msisdn",),
                        name="uniq_active_wa_msisdn",
                    )
                ],
            },
        ),
    ]
