# Generated by Django 5.2.14 on 2026-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.CharField(blank=True, default="", max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
