# Generated by Django 5.2.15 on 2026-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_auditlog_broadcast_broadcastrecipient_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created"], name="auditlog_created_idx"),
        ),
        migrations.AddIndex(
            model_name="wamessagelog",
            index=models.Index(
                fields=["msisdn", "-created"], name="wamsg_msisdn_created_idx"
            ),
        ),
    ]
