# Generated by Django 5.2.15 on 2026-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "whatsapp",
            "0004_auditlog_audit_created_idx_auditlog_audit_action_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WaOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msisdn", models.CharField(db_index=True, max_length=20, unique=True)),
                ("step", models.CharField(max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
