# Generated by Django 5.2.16 on 2026-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0005_waonboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=40)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("rejected_token", "rejected_token"),
                            ("rejected_ip", "rejected_ip"),
                            ("rejected_signature", "rejected_signature"),
                            ("rejected_method", "rejected_method"),
                            ("bad_body", "bad_body"),
                        ],
                        default="accepted",
                        max_length=24,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("http_status", models.PositiveSmallIntegerField(default=200)),
                ("remote_ip", models.CharField(blank=True, default="", max_length=64)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("action", models.CharField(blank=True, default="", max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["-created"], name="webhook_created_idx"),
                    models.Index(fields=["source"], name="webhook_source_idx"),
                    models.Index(fields=["reference"], name="webhook_reference_idx"),
                ],
            },
        ),
    ]
