# Generated by Django 5.2.16 on 2026-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0009_whatsapp_durable_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationstate",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
