# Generated by Django 5.2.16 on 2026-08-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0010_conversationstate_last_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapplink",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
