# Generated by Django 5.2.17 on 2026-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0012_enable_ai_for_existing_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationstate",
            name="last_txn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationstate",
            name="last_txn_ref",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
