# Generated by Django 5.2.17 on 2026-09-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0014_scansession"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wamessagelog",
            index=models.Index(
                condition=models.Q(("direction", "in"), ("processed_at__isnull", True)),
                fields=["created"],
                name="wamsg_inbound_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wamessagelog",
            index=models.Index(
                condition=models.Q(("direction", "in"), ("processed_at__isnull", True)),
                fields=["msisdn", "created"],
                name="wamsg_inbound_pending_idx",
            ),
        ),
    ]
