# Generated by Django 5.2.17 on 2026-08-20 12:29

"""Two columns on a table every payout writes to, so both are metadata-only.

Each AddField carries a constant default, which Postgres 11+ records without
rewriting the table — no long lock on transfers_beneficiary while a deploy runs.
That matters here more than usual: execute_payout writes this table AFTER the
money has left the wallet and the rail has accepted it, so a migration that
blocked an INSERT would strand a customer on a spinner for a transfer that had
already gone through.

There is deliberately no unique index on nickname. Enforcing one would mean
CREATE UNIQUE INDEX against that same hot table, and uniqueness is not what makes
paying by name safe — refusing to act on an ambiguous name is, which the lookup
does regardless of what the table allows.

No data migration: existing rows becoming saved=False is the intended reading.
They are recents, because no customer has ever been asked to save them.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0002_bank_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
