# Generated by Django 5.2.17 on 2026-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0003_beneficiary_nickname_beneficiary_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="save_prompted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="times_paid",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
