# Generated by Django 5.1.15 on 2026-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CablePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("1", "GoTV"), ("2", "DSTV"), ("3", "StarTimes")],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "validity",
                    models.CharField(blank=True, default="30 days", max_length=40),
                ),
                ("cable_plan_code", models.CharField(max_length=40, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("1", "MTN"),
                            ("2", "GLO"),
                            ("3", "Airtel"),
                            ("4", "9mobile"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("1", "SME"),
                            ("2", "SME2"),
                            ("3", "Gifting"),
                            ("4", "Corporate"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("validity", models.CharField(max_length=40)),
                ("plan_code", models.CharField(max_length=40, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
