# Generated by Django 5.2.16 on 2026-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cableplan",
            name="wema_code",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="dataplan",
            name="wema_code",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
