# Generated by Django 5.2.17 on 2026-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility", "0002_cableplan_wema_code_dataplan_wema_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="WemaBiller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=60, unique=True)),
                ("package_id", models.CharField(max_length=60)),
                ("biller_id", models.CharField(blank=True, default="", max_length=60)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
