# Generated by Django 5.2.17 on 2026-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_wemabiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='wemabiller',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='wemabiller',
            name='service_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='wemabiller',
            constraint=models.UniqueConstraint(fields=('service_id', 'meter_type'), name='uniq_wema_biller_variant'),
        ),
        migrations.AddConstraint(
            model_name='wemabiller',
            constraint=models.CheckConstraint(condition=models.Q(('meter_type__in', ['', 'prepaid', 'postpaid'])), name='wema_biller_variant_valid'),
        ),
    ]
