# Generated by Django 5.2.15 on 2026-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrequest",
            name="reference",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
