# Generated by Django 5.2.15 on 2026-07-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convert", "0002_alter_conversionrequest_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
