# Generated by Django 5.1.15 on 2026-05-31 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("principal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("interest", models.DecimalField(decimal_places=2, max_digits=14)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("matured", "Matured")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("paid_out", models.BooleanField(default=False)),
                ("matures_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
