# Generated by Django 5.2.15 on 2026-06-10 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fixedsave",
            index=models.Index(
                fields=["status", "paid_out", "matures_at"], name="fixedsave_sweep_idx"
            ),
        ),
    ]
