# Generated by Django 5.2.14 on 2026-06-01 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcard",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="card_token",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
