# Generated by Django 5.2.17 on 2026-10-05 12:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_identityproof_verified_name'),
        ('wallet', '0024_bankhistorycheckpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('encrypted_identity', models.TextField()),
                ('verification_reference', models.CharField(max_length=160)),
                ('consent_reference', models.CharField(max_length=160)),
                ('verified_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('validation', 'validation'), ('live', 'live')], max_length=10)),
                ('prefix', models.CharField(max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('validation_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vas_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('payment_reference', models.CharField(max_length=128, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_account', models.CharField(max_length=10)),
                ('source_bank', models.CharField(max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('credited', 'credited'), ('validation', 'validation'), ('held', 'held')], max_length=10)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vas_receipt', to='wallet.transaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='wema_vas.virtualaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.CheckConstraint(condition=models.Q(('validation_balance__gte', 0)), name='vas_validation_balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'validation'), ('validation_balance', 0), _connector='OR'), name='vas_live_no_validation_balance'),
        ),
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'validation'), ('prefix', '711')), models.Q(('mode', 'live'), models.Q(('prefix', '711'), _negated=True)), _connector='OR'), name='vas_mode_prefix_separate'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['account', 'occurred_at'], name='vas_receipt_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='vas_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'credited'), ('transaction__isnull', False)), models.Q(('state__in', ['held', 'validation']), ('transaction__isnull', True)), _connector='OR'), name='vas_receipt_ledger_binding'),
        ),
    ]
