# Generated by Django 5.2.17 on 2026-10-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wema_vas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='cutover_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='MigrationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=160)),
                ('approved_by', models.CharField(max_length=160)),
                ('legacy_account_number', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vas_migration_approval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
