# Generated by Django 5.2.17 on 2026-10-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wema_vas', '0003_durable_bank_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vas_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.UniqueConstraint(fields=('user', 'mode'), name='vas_user_mode_unique'),
        ),
    ]
